import mongoose from "mongoose";

const paymentSchema = new mongoose.Schema(
  {
    student: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },

    course: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Course",
      required: true,
    },

    amount: {
      type: Number,
      required: true,
    },

    // UUID generated by your backend
    transactionId: {
      type: String,
      required: true,
      unique: true,
      index: true,
    },

    // Transaction code returned by eSewa after successful payment
    esewaTransactionId: {
      type: String,
      unique: true,
      sparse: true,
    },

    paymentMethod: {
      type: String,
      enum: ["esewa"],
      default: "esewa",
    },

    status: {
      type: String,
      enum: ["pending", "completed", "failed", "refunded"],
      default: "pending",
    },

    paidAt: {
      type: Date, 
    },
  },
  {
    timestamps: true,
  }
);

export default mongoose.model("Payment", paymentSchema);